# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-11 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='../static/images/noimage.svg', null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('live', models.CharField(max_length=100)),
            ],
        ),
    ]
